package uz.technocorp.ecosystem.modules.template;

/**
 * @author Sukhrob
 * @version 1.0
 * @created 23.04.2025
 * @since v1.0
 */
public enum TemplateType {
    // Appeal
    IRS_APPEAL,

    // XICHO
    XICHO_APPEAL,
    DEREGISTER_HF_APPEAL,

    // Equipment,
    EQUIPMENT_APPEAL,
    DEREGISTER_EQUIPMENT_APPEAL,
    REREGISTER_EQUIPMENT_APPEAL,

    ATTRACTION_PASSPORT_APPEAL,
    ATTESTATION_LEADER_APPEAL,
    ATTESTATION_EMPLOYEE_APPEAL,
    CADASTRE_PASSPORT_APPEAL,
    DECLARATION_APPEAL,
    ACCREDITATION_APPEAL,
    RE_ACCREDITATION_APPEAL,
    EXPEND_ACCREDITATION_APPEAL,
    EXPERTISE_CONCLUSION_APPEAL,

    // Reestr
    REGISTRY_HF,
    REGISTRY_EQUIPMENT,
    REGISTRY_ATTRACTION,
    REGISTRY_ATTRACTION_PASSPORT,

    // Inspektor javob xati ( Ma'lumotnoma )
    REPLY_HF_APPEAL,
    REPLY_HF_DEREGISTER_APPEAL,
    REPLY_IRS_APPEAL,
    REPLY_EQUIPMENT_APPEAL,
    REPLY_ATTRACTION_PASSPORT_APPEAL,
    REPLY_INSPECTION_REPORT,

    // Arizani rad etish
    REJECT_APPEAL,

    // Attestatsiyaga Qo'mita va Huduiy bo'lim javob xati
    REPLY_COMMITTEE_TO_APPEAL,
    REPLY_REGIONAL_TO_APPEAL,

    //Kadastrga qo'mita javob xati
    REPLY_ACCEPT_CADASTRE_PASSPORT_APPEAL,
    REPLY_ACCEPT_DECLARATION_APPEAL,
    REPLY_REJECT_CADASTRE_PASSPORT_APPEAL,
    REPLY_REJECT_DECLARATION_APPEAL,

    // Accreditation
    ACCREDITATION_CERTIFICATE,
    ACCREDITATION_CONCLUSION

}
